# Imagen base de Node
FROM node:20

# Crear carpeta de la app
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto de la app
COPY . .

# Puerto expuesto
EXPOSE 3000

# Comando para arrancar la app
CMD ["npm", "start"]
