version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: apidb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  api:
    build: .
    container_name: api_node
    command: npm start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
